--- Dockerfile.orig	2017-05-11 08:38:23.888649044 +0800
+++ Dockerfile	2017-05-11 08:39:11.016647956 +0800
@@ -27,7 +27,14 @@
 
 # allow replacing httpredir or deb mirror
 ARG APT_MIRROR=deb.debian.org
-RUN sed -ri "s/(httpredir|deb).debian.org/$APT_MIRROR/g" /etc/apt/sources.list
+RUN sed -ri "s/(httpredir|deb).debian.org/linux-ftp.sh.intel.com\/pub\/mirrors/g" /etc/apt/sources.list
+ 
+ENV http_proxy "http://proxy-shz.intel.com:911/"
+ENV https_proxy "https://proxy-shz.intel.com:911/"
+ENV ftp_proxy "http://proxy-shz.intel.com:911/"
+ENV no_proxy "localhost,127.0.0.1,.intel.com"
+ 
+RUN apt-get clean
 
 # Add zfs ppa
 COPY keys/launchpad-ppa-zfs.asc /go/src/github.com/docker/docker/keys/
@@ -235,7 +242,6 @@
 # Get useful and necessary Hub images so we can "docker load" locally instead of pulling
 COPY contrib/download-frozen-image-v2.sh /go/src/github.com/docker/docker/contrib/
 RUN ./contrib/download-frozen-image-v2.sh /docker-frozen-images \
-	buildpack-deps:jessie@sha256:85b379ec16065e4fe4127eb1c5fb1bcc03c559bd36dbb2e22ff496de55925fa6 \
 	busybox:latest@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f \
 	debian:jessie@sha256:72f784399fd2719b4cb4e16ef8e369a39dc67f53d978cd3e2e7bf4e502c7b793 \
 	hello-world:latest@sha256:c5515758d4c5e1e838e9cd307f6c6a0d620b5e07e6f927b07d05f6d12a1ac8d7
